version: '3.2'

services:
  psql:
    container_name: psql
    image: postgres:13
    restart: unless-stopped
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - ./:/var/lib/postgresql