version: '3.9'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  celery:
    build: ./app
    command: celery -A core worker -l INFO
    volumes:
      - ./app/:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - web
      - redis
  flower:
    build: ./app
    command: celery -A core flower --address=0.0.0.0 --port=5566
    ports:
      - "5566:5566"
    volumes:
      - ./app/:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - celery
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  redis:
    image: "redis:alpine"

volumes:
  postgres_data: