# Generated by Django 4.0.3 on 2022-03-20 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receiving', to=settings.AUTH_USER_MODEL)),
                ('payer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paying', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
