# Generated by Django 4.0.3 on 2022-03-21 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_personalaccount_alter_transaction_payee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='personal balance'),
        ),
    ]
